"""add bookings and user address

Revision ID: 8d7512570390
Revises: 3afb09716417
Create Date: 2026-08-31 05:58:58.526914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7512570390'
down_revision: Union[str, None] = '3afb09716417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'COMPLETED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['professional_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    message_type_enum = sa.Enum('TEXT', 'BOOKING', name='message_type')
    message_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('message_type', message_type_enum, nullable=False, server_default='TEXT'))
    op.alter_column('messages', 'message_type', server_default=None)
    op.add_column('messages', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'booking_id')
    op.drop_column('messages', 'message_type')
    sa.Enum(name='message_type').drop(op.get_bind(), checkfirst=True)
    op.drop_table('booking_items')
    op.drop_table('bookings')
    # ### end Alembic commands ###
